[package]
name = "rustdemo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
libc = "0.2.112"

log = "0.4.14"
android_logger = "0.10"
ndk = "0.6.0"
jni = { version = "0.19.0", default-features = false }